# Generated by Django 5.0.3 on 2024-03-21 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_likes', models.PositiveIntegerField(default=0)),
                ('title', models.TextField(default='', max_length=255)),
                ('body', models.TextField(max_length=35000, null=True)),
                ('url', models.TextField(default='', max_length=35000)),
                ('author', models.ForeignKey(default='default_user', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
