# Generated by Django 4.1.13 on 2024-04-15 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magazine',
            name='description',
        ),
    ]
