# Generated by Django 5.0.3 on 2024-03-21 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='creation_data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
