# Generated by Django 4.1.13 on 2024-04-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
