# Generated by Django 5.0.3 on 2024-04-10 17:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_thread_creation_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=35000, null=True)),
                ('creation_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_likes', models.PositiveIntegerField(default=0)),
                ('num_dislikes', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(default='default_user', on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('thread', models.ForeignKey(default='default_thread', on_delete=django.db.models.deletion.CASCADE, to='api.thread')),
            ],
        ),
    ]
