# Generated by Django 5.0.4 on 2024-04-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_publicacio_magazine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magazine',
            name='description',
            field=models.TextField(max_length=40000, null=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='name',
            field=models.CharField(max_length=25000, unique=True),
        ),
        migrations.AlterField(
            model_name='magazine',
            name='title',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='publicacio',
            name='title',
            field=models.TextField(default='', max_length=25500),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='', max_length=10000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover',
            field=models.ImageField(default='', max_length=10000, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
