# Generated by Django 4.1.13 on 2024-04-11 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_reply', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply_comments', to='api.comment')),
                ('comment_root', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_comments', to='api.comment')),
            ],
            options={
                'unique_together': {('comment_root', 'comment_reply')},
            },
        ),
    ]
