"""
Django settings for projecte_asw project.

Generated by 'django-admin startproject' using Django 4.1.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
from corsheaders.defaults import default_headers

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+9)qx*(waqx7qc8ndjhmu#6pr_24jr4=cuj(_e4#n1=*po4ilq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['bravo13-36a68ba47d34.herokuapp.com', '127.0.0.1']

# Application definition

SITE_ID = 5

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'kbin',
    'rest_framework',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'storages',
    "api.apps.ApiConfig",
    'corsheaders',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'kbin.middleware.AddUserToContextMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True  # Permitir solicitudes de cualquier origen
# CORS_ALLOW_HEADERS = ["keyword"]
# CORS_ALLOW_ALL_HEADERS = True

CORS_ALLOW_HEADERS = (
    *default_headers,
    "keyword",
)

ROOT_URLCONF = 'projecte_asw.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'kbin.context_processors.usuari_context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'projecte_asw.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

# Obtener la URL de la base de datos de la variable de entorno
DATABASE_URL = os.environ.get('DATABASE_URL')

# Configurar las bases de datos
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (css, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

# STATIC_URL = 'static/'
# STATIC_ROOT = ''
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_URL = '/static/'
STATICFILES_DIRS = ('static',
                    os.path.join(BASE_DIR, 'static', 'fonts'))

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)

# &redirect_uri=login

SOCIALACCOUNT_LOGIN_ON_GET = True
LOGIN_URL = '/accounts/google/login'
LOGIN_REDIRECT_URL = '/login'
SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

# S3 settings

AWS_ACCESS_KEY_ID = 'ASIA6GBMBUJHHEZU2KOP'
AWS_SECRET_ACCESS_KEY = 'xhRTjsUwaqPq6YfHZAPiZiZ4Rr/Hk0NNXDzhSYTz'
AWS_SESSION_TOKEN = 'IQoJb3JpZ2luX2VjELb//////////wEaCXVzLXdlc3QtMiJHMEUCIGUCGGNnM5Hm2JC5TXkuaife8a+M7cocD/vtX41YE4mKAiEA/lnec9T9sbqd93Bw0P0Y/RWUn4g0elTJpleTsmL2UVgquQIIPxAAGgw5NzUwNDk5NTc5NjYiDMkZllBL5s1tPwHsoSqWAmAIJ+N4Q5s1zMXgQkLaaAuU/CKDgXIYfVIqKHfP2j9YETj3VuZw0K/4yfHBy7MRlwOmO8FOui6HxQ/67y8gSwbWoup80IVEtKqx+O7UCfcTfY5dMT7xgMxTzs8nvetprHmAItbcyhTjoGwO9bhg1IPnKkE7oib/Qd8Rzvt0/YGd5duOy35Rp5d64zJ4OdqXcfvoCYWFIjyQxvi9aXRcs8IvdcMqxPiLMXJXBzpGXH8c45pDKjtcCekC/5LkoFv6Dff9V9sHFNFr+X4Q6AKEFqrxxNAtCUZwUjkMlMLUiFSh89OJA3lq+qVvT2/Onb2hgo/1m4HXZ+0f9W8ZqbWjgNgFyWXctRczMat4FEmlxVwDCF4ZFJo+MIDS5bIGOp0BUpYURkyRK4vnd3Kg9G5lJtD1Y6ept+61J1vDPx+K/YrJvUD1Ep8yXNRkxnOf2Ahvgstl/wlc5q/sohUZHFzGq5arjTe8p9quCZh2xPRPyZmErCQKsE1BGMG3rSCUFphQ2e5ftWf+ovtvXy3iFkM3CriF/X6/nwOIv9Vx5IvqPss5bilcv9WutgF4yH5ytWhg/+aC0+76f9A+8h2CNQ=='
AWS_STORAGE_BUCKET_NAME = 'bravo13-bucket'

# Configura el almacenamiento predeterminado para utilizar S3
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

AVATAR_URL = 's3://bravo13-bucket/avatar/'
COVER_URL = 's3://bravo13-bucket/cover/'
